version: "3.9"

services:
  db:
    image: postgres:15
    container_name: report_db
    restart: always
    environment:
      POSTGRES_DB: report_agent_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: report_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./backend/.env
    environment:
      # Ensures docker backend always hits the docker db flawlessly
      DB_URL: postgresql://postgres:password@db:5432/report_agent_db

  frontend:
    build: ./frontend
    container_name: report_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000

volumes:
  pgdata: